import type { Metadata } from "next";
import { Open_Sans, Zalando_Sans_Expanded } from "next/font/google";
import "./globals.css";

const bodyFont = Open_Sans({
  variable: "--font-body",
  subsets: ["latin"],
});

const displayFont = Zalando_Sans_Expanded({
  variable: "--font-display",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${displayFont.variable} ${bodyFont.variable} antialiased bg-background text-foreground font-body font-normal leading-normal p-0`}
      >
        <main>{children}</main>
      </body>
    </html>
  );
}
